# Site settings
title: "Olivia Roscow"
description: "Olivia Roscow's CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Olivia Roscow"
resume_title:                   "Research Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "spyrolivia@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(519) 731-3881"
resume_contact_address:         "Guelph, Canada"

resume_header_contact_info:     "Guelph, Canada • (519) 731-3881 • spyrolivia@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a biochemistry, biophysics, and overall molecular biology enthusiast currently looking for work as either a Research Technician or PhD candidate in a lab that specialises in these areas. Ultimately, my mission is to aid like-minded researchers in achieving their research goals.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/oroscow"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/olivia.roscow/"
  resume_linkedin_url:          "https://www.linkedin.com/in/oliviaroscow/"
  resume_instagram_url:         "https://www.instagram.com/_zhaoliya_/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
