title: Olivia Roscow
description: Biochemistry & Biophysics & Molecular Biology Enthusiast
locale: en_US

owner:
  name: Olivia Roscow
  bio: Biochemistry, Biophysics, & Molecular Biology Enthusiast
  email: spyrolivia@gmail.com
  linkedin: Olivia Roscow
  github: oroscow
  orcid: 0000-0002-1753-6579
  
